### ISSUE TITLE
FIFO buffer not enabled

### ISSUE THREAD

**Issue by dansitu** [arduino-libraries/Arduino_LSM9DS1#3]
The library does not currently enable the accelerometer's FIFO buffer, resulting in many skipped samples unless the sensor is polled rapidly enough. We require the FIFO buffer in the TensorFlow Lite for Microcontrollers "magic wand" example, so I've written instructions for patching the library in the following readme:

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/magic_wand#install-and-patch-the-accelerometer-driver

While my patch just returns a "1" if data is available, it might be better to return the actual count of bytes in the buffer from `LSM9DS1Class::accelerationAvailable()`.

**Comment by facchinm** [comment]
@sandeepmistry worth patching the library to support FIFO for everyone?

**Comment by sandeepmistry** [comment]
Hi @dansitu,

Thanks for the suggestion!

However, from reading the datasheet things seem a little more complicated. It appears both the accelerometer and gyroscope readings would be stored in the FIFO when enabled. This means, `gyroscopeAvailable()` would also be impacted.

Some options:
1) have `readAcceleration` and `readGyroscope` read all acceleration + gyro data at once and "cache" the other as needed.

2) `1)` but only enabled if `IMU.enableFIFO()` is called

3) Add a new method to read acceleration + gyro data at once

4) `<your suggestion goes here>`

@facchinm @dansitu @8bitkick please let me know your thoughts on above :)

**Comment by dansitu** [comment]
Ah, that's interesting! Maybe `IMU.enableFIFO()` should accept an arg that tells it which data we're interested in (acceleration, gyro, or both). If acceleration is chosen, any gyro data is discarded, and vice versa. This would help avoid using memory for caching if we're only interested in one type of data?

**Comment by cmaglie** [comment]
@dansitu we just released 1.1.0 with #6 merged that should address this issue. Would you like giving a try?

**Comment by dansitu** [comment]
I've moved on from the TensorFlow Lite team, but @petewarden may be interested—Pete, this is a fix that should simplify deployment for the magic_wand example by avoiding the need to modify the Arduino accelerometer driver.

**Comment by petewarden** [comment]
Thanks @dansitu - I was actually the author of #6 :)

**Comment by dansitu** [comment]
Haha, excellent :) In that case @cmaglie I think this issue can be closed!
